endroid_qr_code:
    default:
        writer: Endroid\QrCode\Writer\PngWriter
        size: 2450
        margin: 270
        encoding: 'UTF-8'
        error_correction_level: 'low'
        round_block_size_mode: 'margin'
        validate_result: false
